"""initial schema

Revision ID: 20f268bc6e01
Revises: 
Create Date: 2025-07-18 09:12:36.633836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f268bc6e01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('gdpr_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('scope', sa.Enum('ALL', 'LEGAL_BASIS', name='actionscope'), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'scope', name='uq_action_label_scope')
    )
    op.create_index(op.f('ix_gdpr_actions_id'), 'gdpr_actions', ['id'], unique=False)
    op.create_table('rgpd_exigences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_exigences_id'), 'rgpd_exigences', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_table('processings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('legal_basis', sa.Enum('Consentement', 'Contrat', 'Obligation légale', 'Intérêt légitime', name='legal_basis_enum'), nullable=False),
    sa.Column('data_subjects', sa.JSON(), nullable=False),
    sa.Column('data_categories', sa.JSON(), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=True),
    sa.Column('dpo_contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processings_id'), 'processings', ['id'], unique=False)
    op.create_table('site_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_documents_site_id'), 'site_documents', ['site_id'], unique=False)
    op.create_table('site_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_photos_site_id'), 'site_photos', ['site_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('certifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('date_obtention', sa.Date(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('organisme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifs_id'), 'certifs', ['id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_table('ouvriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('poste', sa.String(), nullable=True),
    sa.Column('formation_a_jour', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ouvriers_id'), 'ouvriers', ['id'], unique=False)
    op.create_table('processing_actions',
    sa.Column('processing_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['gdpr_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_id'], ['processings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('processing_id', 'action_id')
    )
    op.create_table('registres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom_traitement', sa.String(), nullable=False),
    sa.Column('finalite', sa.Text(), nullable=False),
    sa.Column('categorie_donnees', sa.Text(), nullable=True),
    sa.Column('categorie_personnes', sa.Text(), nullable=True),
    sa.Column('base_legale', sa.String(), nullable=True),
    sa.Column('duree_conservation', sa.String(), nullable=True),
    sa.Column('mesures_securite', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registres_id'), 'registres', ['id'], unique=False)
    op.create_index(op.f('ix_registres_user_id'), 'registres', ['user_id'], unique=False)
    op.create_table('rgpd_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('conforme', sa.Integer(), nullable=False),
    sa.Column('non_conforme', sa.Integer(), nullable=False),
    sa.Column('critical_ko', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_audits_company_id'), 'rgpd_audits', ['company_id'], unique=False)
    op.create_index(op.f('ix_rgpd_audits_id'), 'rgpd_audits', ['id'], unique=False)
    op.create_index(op.f('ix_rgpd_audits_user_id'), 'rgpd_audits', ['user_id'], unique=False)
    op.create_table('securite_controles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('societe_id', sa.Integer(), nullable=True),
    sa.Column('date_controle', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('nb_nc', sa.Integer(), nullable=True),
    sa.Column('rapport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['societe_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securite_controles_id'), 'securite_controles', ['id'], unique=False)
    op.create_index(op.f('ix_securite_controles_site_id'), 'securite_controles', ['site_id'], unique=False)
    op.create_index(op.f('ix_securite_controles_societe_id'), 'securite_controles', ['societe_id'], unique=False)
    op.create_index(op.f('ix_securite_controles_user_id'), 'securite_controles', ['user_id'], unique=False)
    op.create_table('rgpd_audit_exigences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['rgpd_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_audit_exigences_id'), 'rgpd_audit_exigences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rgpd_audit_exigences_id'), table_name='rgpd_audit_exigences')
    op.drop_table('rgpd_audit_exigences')
    op.drop_index(op.f('ix_securite_controles_user_id'), table_name='securite_controles')
    op.drop_index(op.f('ix_securite_controles_societe_id'), table_name='securite_controles')
    op.drop_index(op.f('ix_securite_controles_site_id'), table_name='securite_controles')
    op.drop_index(op.f('ix_securite_controles_id'), table_name='securite_controles')
    op.drop_table('securite_controles')
    op.drop_index(op.f('ix_rgpd_audits_user_id'), table_name='rgpd_audits')
    op.drop_index(op.f('ix_rgpd_audits_id'), table_name='rgpd_audits')
    op.drop_index(op.f('ix_rgpd_audits_company_id'), table_name='rgpd_audits')
    op.drop_table('rgpd_audits')
    op.drop_index(op.f('ix_registres_user_id'), table_name='registres')
    op.drop_index(op.f('ix_registres_id'), table_name='registres')
    op.drop_table('registres')
    op.drop_table('processing_actions')
    op.drop_index(op.f('ix_ouvriers_id'), table_name='ouvriers')
    op.drop_table('ouvriers')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_certifs_id'), table_name='certifs')
    op.drop_table('certifs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_photos_site_id'), table_name='site_photos')
    op.drop_table('site_photos')
    op.drop_index(op.f('ix_site_documents_site_id'), table_name='site_documents')
    op.drop_table('site_documents')
    op.drop_index(op.f('ix_processings_id'), table_name='processings')
    op.drop_table('processings')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_rgpd_exigences_id'), table_name='rgpd_exigences')
    op.drop_table('rgpd_exigences')
    op.drop_index(op.f('ix_gdpr_actions_id'), table_name='gdpr_actions')
    op.drop_table('gdpr_actions')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
