"""empty message

Revision ID: 63ac8e1a89fa
Revises: 6e2cc32a9c72
Create Date: 2025-07-03 18:21:58.373288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ac8e1a89fa'
down_revision: Union[str, None] = '6e2cc32a9c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rgpd_requirements')
    op.add_column('gdpr_actions', sa.Column('advice', sa.Text(), nullable=True))
    op.add_column('gdpr_actions', sa.Column('critical', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gdpr_actions', 'critical')
    op.drop_column('gdpr_actions', 'advice')
    op.create_table('rgpd_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('article', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('advice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('critical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rgpd_requirements_pkey'))
    )
    # ### end Alembic commands ###
