"""add created_at to registres

Revision ID: 8f56329a49d5
Revises: 20f268bc6e01
Create Date: 2025-07-18 14:05:30.021306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f56329a49d5'
down_revision: Union[str, None] = '20f268bc6e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registres', sa.Column('personnes_concernees', sa.Text(), nullable=True))
    op.add_column('registres', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('registres', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('registres', 'base_legale',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('registres', 'duree_conservation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('registres', 'categorie_personnes')
    op.drop_column('registres', 'date_creation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registres', sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('registres', sa.Column('categorie_personnes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('registres', 'duree_conservation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('registres', 'base_legale',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('registres', 'updated_at')
    op.drop_column('registres', 'created_at')
    op.drop_column('registres', 'personnes_concernees')
    # ### end Alembic commands ###
