"""add register table

Revision ID: a3acb8046226
Revises: 18aed20e72ab
Create Date: 2025-07-11 15:31:45.444878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3acb8046226'
down_revision: Union[str, None] = '18aed20e72ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dpo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('designation_date', sa.Date(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpo_id'), 'dpo', ['id'], unique=False)
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom_traitement', sa.String(), nullable=False),
    sa.Column('finalite', sa.String(), nullable=True),
    sa.Column('base_legale', sa.String(), nullable=True),
    sa.Column('personnes_concernees', sa.String(), nullable=True),
    sa.Column('duree_conservation', sa.String(), nullable=True),
    sa.Column('dpo_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dpo_id'], ['dpo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registers_id'), 'registers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registers_id'), table_name='registers')
    op.drop_table('registers')
    op.drop_index(op.f('ix_dpo_id'), table_name='dpo')
    op.drop_table('dpo')
    # ### end Alembic commands ###
