"""Ajout RGPD

Revision ID: f0c7eddfa7a6
Revises: 6454952db24b
Create Date: 2025-07-07 12:04:51.309548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c7eddfa7a6'
down_revision: Union[str, None] = '6454952db24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rgpd_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_audits_company_id'), 'rgpd_audits', ['company_id'], unique=False)
    op.create_index(op.f('ix_rgpd_audits_id'), 'rgpd_audits', ['id'], unique=False)
    op.create_index(op.f('ix_rgpd_audits_user_id'), 'rgpd_audits', ['user_id'], unique=False)
    op.create_table('rgpd_exigences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_exigences_id'), 'rgpd_exigences', ['id'], unique=False)
    op.create_table('gdpr_action_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['gdpr_actions.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['rgpd_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdpr_action_answers_id'), 'gdpr_action_answers', ['id'], unique=False)
    op.create_table('rgpd_audit_exigences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('exigence_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['rgpd_audits.id'], ),
    sa.ForeignKeyConstraint(['exigence_id'], ['rgpd_exigences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rgpd_audit_exigences_id'), 'rgpd_audit_exigences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rgpd_audit_exigences_id'), table_name='rgpd_audit_exigences')
    op.drop_table('rgpd_audit_exigences')
    op.drop_index(op.f('ix_gdpr_action_answers_id'), table_name='gdpr_action_answers')
    op.drop_table('gdpr_action_answers')
    op.drop_index(op.f('ix_rgpd_exigences_id'), table_name='rgpd_exigences')
    op.drop_table('rgpd_exigences')
    op.drop_index(op.f('ix_rgpd_audits_user_id'), table_name='rgpd_audits')
    op.drop_index(op.f('ix_rgpd_audits_id'), table_name='rgpd_audits')
    op.drop_index(op.f('ix_rgpd_audits_company_id'), table_name='rgpd_audits')
    op.drop_table('rgpd_audits')
    # ### end Alembic commands ###
