# .github/workflows/ci.yml dans conformeo-backend
name: CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      - name: Lint & format check
        run: |
          flake8 app tests
          black --check .

      - name: Run tests
        env:
          # Utilise SQLite in-memory pour les tests
          DATABASE_URL: "sqlite:///:memory"
          SECRET_KEY: "testsecret"
        run: pytest --maxfail=1 --disable-warnings -q
